services:
  db:
    container_name: sosiska_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=sosiska
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'" ]
      interval: 10s
      timeout: 5s
      retries: 5
#    volumes:
#      - ./db:/var/lib/postgresql/data

  sosiska_api:
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

    build:
      context: .
      dockerfile: Dockerfile